resources:

- name: bts-repo
  type: git
  source:
    uri: git@github.com:griga23/boot-twitter-sentiment.git
    branch: master
    private_key: {{bts_private_key}}

- name: visualizer-release
  type: s3
  source:
    bucket: griga-boot-twitter-sentiment
    regexp: boot-twitter-visualizer-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: feeder-release
  type: s3
  source:
    bucket: griga-boot-twitter-sentiment
    regexp: boot-twitter-feeder-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: cf-test
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space-test}}
    skip_cert_check: true

- name: cf-prod
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space-prod}}
    skip_cert_check: true

- name: version
  type: semver
  source:
    bucket: griga-boot-twitter-sentiment
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    initial_version: 1.0.0

jobs:
- name: unit-test
  plan:
  - get: bts-repo
    trigger: true
  - task: unit
    file: bts-repo/ci/tasks/unit.yml

- name: build-binary
  plan:
  - get: bts-repo
    passed: [unit-test]
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build-artifact
    file: bts-repo/ci/tasks/build-artifact.yml
    timeout: 5m
  - put: feeder-release
    params: {file: binaries/boot-twitter-feeder*.jar }
  - put: visualizer-release
    params: {file: binaries/boot-twitter-visualizer*.jar }
  - put: bts-repo
    params:
      repository: bts-repo
      tag: version/number
  - put: version
    params: {file: version/number}

- name: acceptance-tests
  plan:
  - get: feeder-release
    passed: [build-binary]
    trigger: true
  - get: visualizer-release
    passed: [build-binary]
  - get: bts-repo
    passed: [build-binary]
    trigger: true
  - put: cf-test
    params:
      manifest: bts-repo/test-manifest.yml
  - task: cats
    file: bts-repo/ci/tasks/test_env.yml

- name: manual-deploy-to-prod
  plan:
  - get: feeder-release
    passed: [acceptance-tests]
    trigger: true
  - get: visualizer-release
    passed: [acceptance-tests]
  - get: bts-repo
    passed: [acceptance-tests]
  - put: cf-prod
    params:
      manifest: music-repo/prod-manifest.yml
