resources:

- name: bts-repo
  type: git
  source:
    uri: git@github.com:griga23/boot-twitter-sentiment.git
    branch: master
    private_key: {{bts_private_key}}

- name: bts-release
  type: s3
  source:
    bucket: griga-boot-twitter-sentiment
    regexp: (.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: bts-cf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

- name: version
  type: semver
  source:
    bucket: griga-boot-twitter-sentiment
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    initial_version: 1.0.0

jobs:
- name: unit-test
  plan:
  - get: bts-repo
    trigger: true
  - task: unit
    file: bts-repo/ci/tasks/unit.yml

- name: build-binary
  plan:
  - get: bts-repo
    passed: [unit-test]
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build-artifact
    file: bts-repo/ci/tasks/build-artifact.yml
    timeout: 5m
  - put: bts-release
    params: {file: binaries/*.jar }
  - put: bts-repo
    params:
      repository: bts-repo
      tag: version/number
  - put: version
    params: {file: version/number}

- name: acceptance-tests
  plan:
  - get: bts-release
    passed: [build-binary]
    trigger: true
  - get: bts-repo
    passed: [build-binary]
    trigger: true
  - put: bts-cf
    params:
      manifest: bts-repo/acc-manifest.yml
      path: bts-release/*.jar
  - task: cats
    file: bts-repo/ci/tasks/cats.yml
